security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    role_hierarchy:
        ROLE_CAN_SWITCH_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
    providers:
        user_switch:
            id: App\Security\UserAPIProvider
        default:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: default
        graphql:
            switch_user:
                provider: default
                parameter: "x-switch-user"
            pattern: ^/graphql
            stateless: true
            jwt:
                provider: default
                authenticator: lexik_jwt_authentication.security.jwt_authenticator
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
